---
language: node_js
node_js:
  - "4"

sudo: required
dist: trusty

addons:
  code_climate:
    repo_token: e3ad0bb7161f6cebc36d385ac707a4998535afa01ce157426571e3d0687e4f85
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

cache:
  directories:
    - node_modules

env:
  - EMBER_TRY_SCENARIO=default

matrix:
  fast_finish: true

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "npm install -g npm@^3"
  - "npm config set progress false"
  - "npm config set spin false"
  - "npm install phantomjs-prebuilt"
  - "npm install -g bower"

install:
  - npm install
  - bower install

script:
  - ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup

branches:
  only:
    - master
